tap "homebrew/cask"
tap "homebrew-ffmpeg/ffmpeg"

brew "youtube-dl"
brew "fdk-aac"
brew "fdk-aac-encoder"
brew "homebrew-ffmpeg/ffmpeg/ffmpeg", args: ["with-fdk-aac", "with-rav1e"]
brew "imagemagick"
brew "libheif"
cask "vlc"
