#!/bin/sh
basedir="`dirname $0`"
NOTMUCH="/usr/bin/notmuch"

$NOTMUCH new #--quiet

$NOTMUCH tag +inbox -- "folder:christo@cryptodrunks.net/cryptodrunks and not tag:inbox"
$NOTMUCH tag +sent -- "folder:christo@cryptodrunks.net/cryptodrunks.Sent and not tag:sent"
$NOTMUCH tag +draft -- "folder:drafts and not tag:draft"
$NOTMUCH tag +cdrunks2 -- "folder:christo@cryptodrunks.net/cryptodrunks and not tag:cdrunks2"
$NOTMUCH tag -inbox +archive -- "folder:christo@cryptodrunks.net/cryptodrunks.Archive and not tag:archive"
$NOTMUCH tag -unread -inbox +trash -- 'folder:christo@cryptodrunks.net/cryptodrunks.Trash'
