source "$HOME"/.antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found
antigen bundle wookayin/fzf-fasd
antigen bundle leophys/zsh-plugin-fzf-finder
antigen bundle hlissner/zsh-autopair

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting

# Tell Antigen that you're done.
antigen apply

# Prefer our own version of md over the alias that comes with oh-my-zsh.
unalias md

[[ -f ~/.rc ]] && source ~/.rc
[[ -f ~/.functions ]] && source ~/.functions
[[ -f ~/.aliases ]] && source ~/.aliases
[[ -f ~/.theme.zsh ]] && source ~/.theme.zsh

# use .localrc for settings specific to one system
[[ -f ~/.localrc ]] && source ~/.localrc
