#!/bin/sh
basedir="`dirname $0`"
NOTMUCH="/usr/bin/notmuch"

$NOTMUCH new #--quiet

$NOTMUCH tag +inbox -- "folder:tacticaltech/tacticaltech and not tag:inbox"
$NOTMUCH tag +sent -- "folder:tacticaltech/INBOX.Sent and not tag:sent"
$NOTMUCH tag +draft -- "folder:drafts and not tag:draft"
$NOTMUCH tag +ttc -- "folder:tacticaltech/tacticaltech and not tag:ttc"
$NOTMUCH tag -inbox +archive -- "folder:tacticaltech/INBOX.Archive and not tag:archive"
$NOTMUCH tag -unread -inbox +trash -- 'folder:tacticaltech/INBOX.Trash'

# TTC Mailinglists
$NOTMUCH tag -inbox +d503 -- "to:d-503@lists.tacticaltech.org and tag:inbox"
$NOTMUCH tag -inbox +berlin -- "to:berlin@tacticaltech.org and tag:inbox"

# The Morning Paper
$NOTMUCH tag -inbox -ttc +morning-paper -- "from:the-morning-paper@onelanday.co.uk and tag:inbox"

# Delete mail marked for deletion
# $NOTMUCH search --output=files tag:deleted | xargs -L 1 rm
