#!/bin/sh
basedir="`dirname $0`"
NOTMUCH="/usr/bin/notmuch"

$NOTMUCH new #--quiet

$NOTMUCH tag +inbox -- "folder:cryptodrunks/crytodrunks and not tag:inbox"
$NOTMUCH tag +inbox -- "folder:tacticaltech/tacticaltech and not tag:inbox"
$NOTMUCH tag +sent -- "folder:cryptodrunks/cryptodrunks.Sent and not tag:sent"
$NOTMUCH tag +sent -- "folder:tacticaltech/INBOX.Sent and not tag:sent"
$NOTMUCH tag +draft -- "folder:drafts and not tag:draft"
$NOTMUCH tag +ttc -- "folder:tacticaltech/tacticaltech and not tag:ttc"
$NOTMUCH tag +cdrunks -- "folder:cryptodrunks/cryptodrunks and not tag:cdrunks"
$NOTMUCH tag -inbox +archive -- "folder:cryptodrunks/cryptodrunks.Archive and not tag:archive"
$NOTMUCH tag -inbox +archive -- "folder:tacticaltech/INBOX.Archive and not tag:archive"
$NOTMUCH tag -unread -inbox +trash -- 'folder:cryptodrunks/cryptodrunks.Trash'
$NOTMUCH tag -unread -inbox +trash -- 'folder:tacticaltech/INBOX.Trash'

# TTC Mailinglists
$NOTMUCH tag -inbox +d503 -- "folder:tacticaltech/tacticaltech and to:d-503@lists.tacticaltech.org and tag:inbox"
$NOTMUCH tag -inbox +berlin -- "folder:tacticaltech/tacticaltech and to:berlin@tacticaltech.org and tag:inbox"

# Haskell mailinglists
$NOTMUCH tag -inbox +haskell -- "folder:cryptodrunks/cryptodrunks and to:haskell@haskell.org and tag:inbox"
$NOTMUCH tag -inbox +haskell-beginners -- "folder:cryptodrunks/cryptodrunks and to:beginners@haskell.org and tag:inbox"
$NOTMUCH tag -inbox +haskell-cafe -- "folder:cryptodrunks/cryptodrunks and to:haskell-cafe@haskell.org and tag:inbox"

# The Morning Paper
$NOTMUCH tag -inbox +morning-paper -- "folder:tacticaltech/tacticaltech and from:the-morning-paper@onelanday.co.uk and tag:inbox"

# Delete mail marked for deletion
# notmuch search --output=files tag:deleted | xargs -L 1 rm
