#!/bin/sh
basedir="`dirname $0`"
NOTMUCH="/usr/bin/notmuch"

$NOTMUCH new #--quiet

$NOTMUCH tag +inbox -- "folder:cryptodrunks/crytodrunks and not tag:inbox"
$NOTMUCH tag +sent -- "folder:cryptodrunks/cryptodrunks.Sent and not tag:sent"
$NOTMUCH tag +draft -- "folder:drafts and not tag:draft"
$NOTMUCH tag +cdrunks -- "folder:cryptodrunks/cryptodrunks and not tag:cdrunks"
$NOTMUCH tag -inbox +archive -- "folder:cryptodrunks/cryptodrunks.Archive and not tag:archive"
$NOTMUCH tag -unread -inbox +trash -- 'folder:cryptodrunks/cryptodrunks.Trash'

# Haskell mailinglists
$NOTMUCH tag -inbox +haskell -- "to:haskell@haskell.org and tag:inbox"
$NOTMUCH tag -inbox +haskell-beginners -- "to:beginners@haskell.org and tag:inbox"
$NOTMUCH tag -inbox +haskell-cafe -- "to:haskell-cafe@haskell.org and tag:inbox"
